name: xdufacool
dependencies:
  - python=3.8
  - pip
  - pip:
    - docx-mailmerge2
    - PyMuPDF
    - PyPDF2[crypto]
  - numpy
  - click
  - xlrd
  - xlwt  
  - lxml  
  - openpyxl
  - conda-forge::pdf2image
  - conda-forge::python-docx
  - conda-forge::python-pptx
  - conda-forge::pyyaml
  - conda-forge::pypandoc
  - conda-forge::mistletoe-ebp
  - conda-forge::bibtexparser
  - conda-forge::pyzotero
