version: "3"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
          
services:
  xdufacool:
    build: .
    image: fredqi/xdufacool:latest
    entrypoint: ["cron", "-f"]
    container_name: xdufacool
    volumes:
      - '/home/data/homeworks:/data'

