networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
          
services:
  xdufacool:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/fredqi/xdufacool:latest
    entrypoint: ["entrypoint.sh"]
    container_name: xdufacool
    environment:
      - WORKDIR=/data
      - TASKFILE=PRML.yml
      - SCHEDULE=7 6-22/3 * * *
    volumes:
      - /home/lectures/machine-learning:/data
