version: "3"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
          
services:
  xdufacool:
    build: .
    image: ghcr.io/fredqi/xdufacool:latest
    entrypoint: ["entrypoint.sh"]
    container_name: xdufacool
    environment:
      - TASKFILE=AISE23.ini
      - SCHEDULE=7 6-22/3 * * *
    volumes:
      - /home/data/homeworks:/data
