name: Unit Tests

on: [push]

jobs:
  testing:
 
    runs-on: ubuntu-${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.8, 3.9]
        os: [18.04, 20.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Unit Tests
      run: |
        python3 -m unittest discover -v

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      if: ${{ always() }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: teaching
        SLACK_ICON_EMOJI: ':mailbox:'
        SLACK_USERNAME: 'GitHub Action Bot'
        SLACK_COLOR: 'good'
        SLACK_TITLE: ${{ github.workflow }}
        SLACK_MESSAGE: "${{ github.workflow }} ${{ job.status }} with Python ${{ matrix.python-version }} on ${{ runner.os }}."
        SLACK_FOOTER: ''
